/** Shared helpers for custom scene layers and edition renderer adapters. */
export { updateActiveGeometry } from './active-geometry.ts'
export { PausedVehicleFrame } from './paused-vehicle-frame.ts'
export { TrailFrameBudget } from './trail-frame-budget.ts'
export { LabelFrameBudget } from './label-frame-budget.ts'
export { StationLabelFrame } from './station-label-frame.ts'
export { VehicleHistory, VEHICLE_TRAIL_HISTORY_LENGTH, VEHICLE_TRAIL_HISTORY_STEP_SECONDS, trailGridMix, trailGridStart } from './vehicle-history.ts'
export { VehicleMotionTable } from './vehicle-motion.ts'
export { MotionSampleWindow, MARKER_SAMPLE_INTERVAL, MARKER_SAMPLE_INTERVAL_REDUCED, MAX_MARKER_STEP_SECONDS, TRAIL_SETTLE_SECONDS, markerStepSeconds } from './motion-sampling.ts'
export type { MotionPass } from './motion-sampling.ts'
export { createMotionLerp, applyMotionLerp } from './motion-lerp.ts'
export type { MotionLerp, MotionLerpProps, MotionMixUniform } from './motion-lerp.ts'
export { createGroundBounds, groundViewBounds, expandBounds, boundsContain, segmentTouchesBounds } from './view-culling.ts'
export type { GroundBounds } from './view-culling.ts'
export { batchHubLines } from './batch-hub-lines.ts'
export { compactMapLines, stationLabelBoxes, emptyLabelBoxes } from './map-cartography.ts'
export type { MapLabelBox } from './map-cartography.ts'
