/** Shared helpers for custom scene layers and edition renderer adapters. */
export { updateActiveGeometry, updateDirtyGeometry } from './active-geometry.ts'
export { PausedVehicleFrame } from './paused-vehicle-frame.ts'
export { TrailFrameBudget } from './trail-frame-budget.ts'
export { LabelFrameBudget } from './label-frame-budget.ts'
export { StationLabelFrame } from './station-label-frame.ts'
export { VehicleHistory, VEHICLE_TRAIL_HISTORY_LENGTH, VEHICLE_TRAIL_HISTORY_STEP_SECONDS, trailGridMix, trailGridStart } from './vehicle-history.ts'
export { VehicleMotionTable, MOTION_STALE, MOTION_MOVING, MOTION_TERMINAL, MOTION_HIDDEN, MOTION_CULLED } from './vehicle-motion.ts'
export type { MotionState } from './vehicle-motion.ts'
export { MotionFrameBudget, MotionCycle, motionLookahead, motionStaleSeconds, MIN_WINDOW_REAL_SECONDS, MAX_CHORD_SECONDS, STALE_REAL_SECONDS, CONVERGE_BUDGET_MS, TRAIL_SETTLE_SECONDS } from './motion-schedule.ts'
export { createMotionLerp, createMotionUniforms, applyMotionLerp } from './motion-lerp.ts'
export type { MotionLerpProps, MotionUniforms } from './motion-lerp.ts'
export { createGroundBounds, groundViewBounds, expandBounds, boundsContain, segmentTouchesBounds } from './view-culling.ts'
export type { GroundBounds } from './view-culling.ts'
export { batchHubLines } from './batch-hub-lines.ts'
export { compactMapLines, stationLabelBoxes, emptyLabelBoxes } from './map-cartography.ts'
export type { MapLabelBox } from './map-cartography.ts'
