import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Airports', exact: false }).click()
})

test('airport boards switch direction, select flights and update values', async ({ page }) => {
  const hero = page.getByRole('region', { name: 'Northfield International', exact: true })
  const departures = hero.getByRole('table', { name: 'NFL Departures' })
  await expect(departures.getByRole('row')).toHaveCount(5)
  const flight = departures.getByRole('button', { name: 'NF 204' })
  await flight.focus()
  await page.keyboard.press('Enter')
  await expect(flight).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('selected-flight')).toHaveText('Selected flight: nf204')
  await page.getByRole('button', { name: 'Update flight' }).click()
  await expect(departures.getByRole('row').filter({ has: page.getByRole('button', { name: 'SA 118' }) })).toContainText('09:15')
  await hero.getByRole('button', { name: 'Arrivals' }).click()
  await expect(hero.getByRole('table', { name: 'NFL Arrivals' }).getByRole('columnheader', { name: 'From', exact: true })).toBeVisible()
  await expect(hero.getByRole('button', { name: 'NF 203' })).toBeVisible()
  await expect(hero.getByRole('button', { name: 'NF 204' })).toHaveCount(0)
  await page.getByLabel('French labels').check()
  await expect(hero.getByRole('button', { name: 'Arrivées' })).toHaveAttribute('aria-pressed', 'true')
  await expect(hero.getByRole('table', { name: 'NFL Arrivées' })).toBeVisible()
  await expect(page.getByRole('table', { name: 'Junction departures' })).toBeVisible()
})

test('study bounds, seeking and the rolling horizon control both directions', async ({ page }) => {
  const hero = page.getByRole('region', { name: 'Northfield International', exact: true })
  await expect(hero).toContainText('Study time 08:32')
  await expect(hero).toContainText('Board window 08:30–09:32')
  await expect(hero.getByRole('button', { name: 'SA 402' })).toHaveCount(0)
  await page.getByLabel('Look ahead').selectOption('7200')
  await expect(hero.getByRole('button', { name: 'SA 402' })).toBeVisible()
  await expect(hero.getByRole('button', { name: /NF (100|900|000)/ })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Study window', exact: true }).selectOption('32400')
  await expect(hero).toContainText('Board window 08:30–09:00')
  await expect(hero.getByRole('table').getByRole('row')).toHaveCount(3)
  await hero.getByRole('button', { name: 'Arrivals' }).click()
  await expect(hero.getByRole('button', { name: 'SA 117' })).toHaveCount(0)
  await page.getByLabel('Airport study time').press('End')
  await expect(hero).toContainText('Study time 09:00')
  await expect(hero.getByRole('button', { name: 'NF 203' })).toHaveCount(0)
  await expect(hero.getByRole('button', { name: 'EA 036' })).toBeVisible()
  await page.getByLabel('Airport study time').press('Home')
  await expect(hero.getByRole('button', { name: 'NF 203' })).toBeVisible()
  await hero.getByRole('button', { name: 'Departures' }).click()
  await expect(hero.getByRole('button', { name: 'NF 204' })).toBeVisible()
})

test('playback updates the card clock and rows, and pause holds the study time', async ({ page }) => {
  await page.clock.install()
  const hero = page.getByRole('region', { name: 'Northfield International', exact: true })
  await page.getByRole('button', { name: 'Play study', exact: true }).click()
  await page.clock.runFor(10000)
  await page.getByRole('button', { name: 'Pause study', exact: true }).click()
  await expect(hero.getByRole('button', { name: 'NF 204' })).toHaveCount(0)
  await expect(hero.getByRole('button', { name: 'SA 402' })).toBeVisible()
  const paused = await page.getByTestId('airport-study-time').textContent()
  await page.clock.runFor(10000)
  await expect(page.getByTestId('airport-study-time')).toHaveText(paused!)
  await page.getByLabel('Airport study time').press('Home')
  await expect(hero.getByRole('button', { name: 'NF 204' })).toBeVisible()
  await expect(hero).toContainText('Study time 08:30')
})

test('empty, loading, failed and incomplete data remain honest', async ({ page }) => {
  const hero = page.getByRole('region', { name: 'Northfield International', exact: true })
  await page.getByLabel('Board state').selectOption('empty')
  await expect(hero.getByRole('status')).toHaveText('No departures in this window.')
  const emptyFlaps = hero.locator('[data-empty] .ms-flap__face')
  const displayedMessage = async () => (await emptyFlaps.allTextContents()).join('').replace(/\s+/gu, ' ').trim()
  expect(await displayedMessage()).toBe('NO DEPARTURES IN THIS WINDOW.')
  await expect(hero.locator('[data-empty] tbody tr')).toHaveCount(2)
  await expect(hero.getByRole('table').getByRole('button')).toHaveCount(0)
  await expect(hero.getByRole('status')).toHaveCount(1)
  await hero.getByRole('button', { name: 'Arrivals' }).click()
  await expect(hero.getByRole('status')).toHaveText('No arrivals in this window.')
  expect(await displayedMessage()).toBe('NO ARRIVALS IN THIS WINDOW.')
  await page.getByLabel('French labels').check()
  expect(await displayedMessage()).toBe('AUCUNE ARRIVÉE DANS CETTE PÉRIODE.')
  await page.getByLabel('French labels').uncheck()
  await page.getByLabel('Board state').selectOption('loading')
  await expect(hero.getByRole('status')).toHaveText('Loading airport movements…')
  await expect(hero.getByRole('table')).toBeVisible()
  await expect(hero.getByRole('table').getByRole('row')).toHaveCount(1)
  await expect(hero.getByRole('table').getByRole('button')).toHaveCount(0)
  await page.getByLabel('Board state').selectOption('error')
  await expect(hero.getByRole('status')).toContainText('Airport movements unavailable.')
  await hero.getByRole('button', { name: 'Retry' }).click()
  await expect(hero.getByRole('table')).toBeVisible()
  await page.getByLabel('Observed tracks only').check()
  const cells = hero.getByRole('row').nth(1).getByRole('cell')
  await expect(cells.nth(2)).toHaveAccessibleName('—')
  await expect(cells.nth(3)).toHaveAccessibleName('—')
  await expect(hero).toContainText('Directions inferred from approach traces.')
})

test('loading characters cycle and settle into real flight details', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  const hero = page.getByRole('region', { name: 'Northfield International', exact: true })
  await page.getByLabel('Board state').selectOption('loading')
  await expect(hero.getByRole('region', { name: 'NFL Departures', exact: true })).toHaveAttribute('aria-busy', 'true')
  const drum = hero.locator('.ms-flap__drum').first()
  // Seek the CSS drum to two positions to check actual character changes deterministically.
  const characters = await drum.evaluate((element) => {
    const cycle = element.getAnimations({ subtree: true }).find((animation) => (animation as CSSAnimation).animationName === 'ms-flap-characters')!
    cycle.pause()
    cycle.currentTime = 0
    const first = getComputedStyle(element, '::before').content
    cycle.currentTime = 480
    return [first, getComputedStyle(element, '::before').content]
  })
  expect(characters[0]).not.toBe(characters[1])
  await expect(hero.locator('.ms-flap__face').first()).toHaveCSS('animation-iteration-count', 'infinite')
  await page.getByLabel('Board state').selectOption('ready')
  await expect(hero.getByRole('region', { name: 'NFL Departures', exact: true })).toHaveAttribute('aria-busy', 'false')
  await expect(hero.getByRole('button', { name: 'NF 204' })).toBeVisible()
  await expect(hero.locator('.ms-flap__drum').first()).toHaveCSS('visibility', 'hidden')
  await expect(hero.locator('.ms-flap__face').first()).toHaveText('0')
  expect(await hero.evaluate((element) => element.getAnimations({ subtree: true }).some((animation) => animation.effect?.getTiming().iterations === Infinity))).toBe(false)
  await page.getByRole('button', { name: 'Reload board', exact: true }).click()
  await expect(hero.getByRole('status')).toHaveText('Loading airport movements…')
  await expect(hero.getByRole('button', { name: 'NF 204' })).toBeVisible()
  await page.getByLabel('Board state').selectOption('loading')
  await page.getByLabel('Board state').selectOption('error')
  await expect(hero.locator('.ms-flap')).toHaveCount(0)
})

test('reduced motion keeps loading flaps still and reveals flight details immediately', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const hero = page.getByRole('region', { name: 'Northfield International', exact: true })
  await page.getByLabel('Board state').selectOption('loading')
  await expect(hero.getByRole('status')).toHaveText('Loading airport movements…')
  await expect(hero.locator('.ms-flap__face').first()).toHaveCSS('animation-name', 'none')
  await expect(hero.locator('.ms-flap__drum').first()).toHaveCSS('display', 'none')
  await page.getByLabel('Board state').selectOption('ready')
  await expect(hero.getByRole('button', { name: 'NF 204' })).toBeVisible()
  await expect(hero.locator('.ms-flap__face').first()).toHaveCSS('animation-name', 'none')
  await expect(hero.locator('.ms-flap__drum').first()).toHaveCSS('display', 'none')
})

test('long names remain accessible, boards contain overflow and respect reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByLabel('Long destination').check()
  const hero = page.getByRole('region', { name: 'Northfield International', exact: true })
  const longName = 'Saint-Étienne International — Terminal Nord'
  await expect(hero.getByRole('cell', { name: longName })).toHaveCount(1)
  await expect(hero.locator('.ms-flap__face').first()).toHaveCSS('animation-name', 'none')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const board = hero.getByRole('region', { name: 'NFL Departures', exact: true })
  await board.focus()
  await expect(board).toBeFocused()
  expect(await board.evaluate((element) => element.scrollWidth >= element.clientWidth)).toBe(true)
  // Updating one flight should retain the focused service button, rather than remounting rows.
  await hero.getByRole('button', { name: 'NF 204' }).focus()
  await page.getByRole('button', { name: 'Update flight' }).evaluate((element: HTMLButtonElement) => element.click())
  await expect(hero.getByRole('button', { name: 'NF 204' })).toBeFocused()
})
