import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Bus boards' }).click()
})

test('both presentations share bus rows, updates and keyboard selection', async ({ page }) => {
  const board = page.getByRole('table', { name: 'Anchor Road bus departures' })
  const route = board.getByRole('button', { name: '71', exact: true })
  await route.focus()
  await page.keyboard.press('Enter')
  await expect(route).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('selected-bus')).toHaveText('Selected bus: bus-0')
  await page.getByRole('button', { name: 'Update bus' }).evaluate((element: HTMLButtonElement) => element.click())
  await expect(route).toBeFocused()
  await expect(board.getByRole('cell', { name: '3 min', exact: true })).toBeVisible()
  await page.getByLabel('Presentation').selectOption('flap')
  await expect(board.getByRole('button', { name: '71', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(board.getByRole('cell', { name: '3 min', exact: true })).toBeVisible()
  await page.getByLabel('Presentation').selectOption('matrix')
  await expect(board.getByRole('button', { name: '71', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('auto rows respond to container height; fixed rows fit without overflow', async ({ page }) => {
  const matrix = page.locator('.ms-dot-matrix-board')
  const frame = page.locator('.bus-board-frame')
  await frame.evaluate((element) => { element.style.height = '240px' })
  await expect(matrix).toHaveAttribute('data-lines', '5')
  await frame.evaluate((element) => { element.style.height = '480px' })
  await expect(matrix).toHaveAttribute('data-lines', '12')
  await page.getByRole('combobox', { name: 'Lines', exact: true }).selectOption('3')
  await expect(matrix.locator('tbody tr')).toHaveCount(3)
  await frame.evaluate((element) => { element.style.height = '260px' })
  await expect(matrix.locator('tbody tr')).toHaveCount(3)
  for (const count of ['6', '15', '30']) {
    await page.getByRole('combobox', { name: 'Lines', exact: true }).selectOption(count)
    await expect(matrix.locator('tbody tr')).toHaveCount(Number(count))
    await expect.poll(() => matrix.locator('.ms-dot-matrix-board__screen').evaluate((element) => element.scrollHeight <= element.clientHeight + 1)).toBe(true)
  }
  await page.getByRole('combobox', { name: 'Lines', exact: true }).selectOption('6')
  await page.getByLabel('Long / multilingual destination').check()
  await expect(matrix.getByRole('cell', { name: 'Saint-Étienne — Gare routière / 中央駅' })).toBeVisible()
  await frame.evaluate((element) => { element.style.width = '280px' })
  await expect.poll(() => matrix.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const screen = matrix.locator('.ms-dot-matrix-board__screen')
  expect(await screen.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
})

test('loading and empty slots expose one status and no selectable stale buses', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const matrix = page.locator('.ms-dot-matrix-board')
  await page.getByLabel('Bus board state').selectOption('loading')
  await expect(matrix.getByRole('table')).toHaveAttribute('aria-busy', 'true')
  await expect(matrix.getByRole('status')).toHaveText('Fetching bus departures…')
  await expect(matrix.getByRole('button')).toHaveCount(0)
  await page.getByLabel('Bus board state').selectOption('empty')
  await expect(matrix.getByRole('status')).toHaveText('No buses expected.')
  await expect(matrix.getByRole('button')).toHaveCount(0)
  await page.getByLabel('Bus board state').selectOption('ready')
  await expect(matrix.getByRole('status')).toHaveCount(0)
  await expect(matrix.getByRole('table')).toHaveAttribute('aria-busy', 'false')
  await expect(matrix.getByRole('button', { name: '71', exact: true })).toBeVisible()
  expect(await matrix.evaluate((element) => element.getAnimations({ subtree: true }).length)).toBe(0)
})
