import { expect, test, type Page } from '@playwright/test'

const runtimeErrors = new WeakMap<Page, string[]>()

test.beforeEach(async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  runtimeErrors.set(page, errors)
})

test.afterEach(async ({ page }) => { expect(runtimeErrors.get(page)).toEqual([]) })

test('themes and pickers work independently of any edition stylesheet', async ({ page }) => {
  await expect(page.getByRole('heading', { name: 'Controls' })).toBeVisible()
  const first = page.getByRole('button', { name: 'cyan service' })
  const second = page.getByRole('button', { name: 'amber service' })
  await first.focus()
  await first.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(first).toContainText('Express')
  await expect(second).toContainText('Express')
  await expect(page.locator('.theme-panel').first()).toHaveCSS('background-color', 'rgb(7, 9, 18)')
  await expect(page.locator('.theme-panel').last()).toHaveCSS('background-color', 'rgb(20, 15, 9)')
  await expect(page.getByRole('button', { name: 'cyan empty' })).toBeDisabled()
  await page.getByLabel('Long labels').check()
  await page.getByLabel('Open upwards').check()
  await second.click()
  await expect(page.getByRole('listbox')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(second).toBeFocused()
})

test('a controlled network supports playback, layouts, selection, layers and remounting', async ({ page }) => {
  await page.getByRole('button', { name: '02 Network' }).click()
  await expect(page.locator('.scene-preview canvas')).toHaveCount(1)
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect.poll(async () => Number((await page.getByTestId('study-time').innerText()).split(' ')[0])).toBeGreaterThan(60)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const paused = await page.getByTestId('study-time').innerText()
  for (const selection of ['route', 'station', 'none', 'service']) {
    await page.getByRole('combobox', { name: 'Selection', exact: true }).selectOption(selection)
    await expect(page.locator('.scene-preview canvas')).toHaveCount(1)
  }
  await page.getByLabel('Layout mix').focus()
  await page.keyboard.press('End')
  await page.getByLabel('Flat routes + quiet ground').check()
  await page.getByLabel('Linked views').check()
  await page.getByLabel('Air + road').check()
  await expect(page.locator('.scene-preview canvas')).toHaveCount(2)
  await page.getByRole('button', { name: 'zoom-in', exact: true }).click()
  await page.getByRole('button', { name: 'reset', exact: true }).click()
  await expect(page.getByTestId('study-time')).toHaveText(paused)
  await page.getByLabel('Empty data').check()
  await expect(page.locator('.scene-preview canvas')).toHaveCount(2)
  for (let count = 0; count < 2; count++) {
    await page.getByRole('button', { name: 'Unmount', exact: true }).click()
    await expect(page.locator('canvas')).toHaveCount(0)
    await page.getByRole('button', { name: 'Mount', exact: true }).click()
    await expect(page.locator('canvas')).toHaveCount(2)
  }
  await expect(page.getByTestId('study-time')).toHaveText(paused)
})

test('hub and track views accept sparse and empty calls', async ({ page }) => {
  await page.getByRole('button', { name: '03 Hub' }).click()
  await expect(page.locator('canvas')).toHaveCount(1)
  for (const trackView of [false, true]) {
    await page.getByLabel('Track view').setChecked(trackView)
    await page.getByRole('button', { name: 'Play', exact: true }).click()
    const start = Number((await page.getByTestId('study-time').innerText()).split(' ')[0])
    await expect.poll(async () => Number((await page.getByTestId('study-time').innerText()).split(' ')[0])).toBeGreaterThan(start)
    await page.getByRole('button', { name: 'Pause', exact: true }).click()
    const paused = await page.getByTestId('study-time').innerText()
    await page.getByLabel('Empty data').check()
    await page.getByLabel('Empty data').uncheck()
    await expect(page.getByTestId('study-time')).toHaveText(paused)
  }
  await page.getByLabel('Empty data').check()
  await page.getByRole('button', { name: 'Unmount', exact: true }).click()
  await expect(page.locator('canvas')).toHaveCount(0)
  await page.getByRole('button', { name: 'Mount', exact: true }).click()
  await expect(page.locator('canvas')).toHaveCount(1)
})

test('the lab displays real loader errors and recovers when its source changes', async ({ page }) => {
  await page.getByRole('button', { name: /Data$/ }).click()
  await page.getByRole('button', { name: 'Enable loader' }).click()
  const output = page.getByTestId('data-status')
  await expect(output).toContainText('Ready')
  await expect(output).toContainText('synthetic-a')
  await page.getByRole('combobox', { name: 'Dataset', exact: true }).selectOption('bad-digest.json')
  await expect(output).toContainText('Error')
  await page.getByRole('combobox', { name: 'Dataset', exact: true }).selectOption('day-b.json')
  await expect(output).toContainText('Ready')
  await expect(output).toContainText('synthetic-b')
  await page.getByRole('button', { name: 'Start polling' }).click()
  await expect(page.getByText('"publisher": "Synthetic source a"', { exact: false })).toBeVisible()
  await page.getByRole('combobox', { name: 'Observation source', exact: true }).selectOption('observations-b.json')
  await expect(page.getByText('"publisher": "Synthetic source b"', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Stop polling' }).click()
})

test('map surfaces and category palettes update an already paused renderer', async ({ page }) => {
  await page.getByRole('button', { name: '02 Network' }).click()
  await page.getByRole('combobox', { name: 'Selection', exact: true }).selectOption('service')
  const canvas = page.locator('.scene-preview canvas')
  const audit = async () => JSON.parse(await canvas.getAttribute('data-style-audit') ?? '{}')
  await expect.poll(async () => (await audit()).labels?.length ?? 0).toBeGreaterThan(0)
  const initial = await audit()
  expect(initial.flatStrokes).toBe(0)
  await page.getByLabel('Alternate category palette').check()
  await expect.poll(async () => JSON.stringify((await audit()).colors)).not.toBe(JSON.stringify(initial.colors))
  await expect.poll(async () => JSON.stringify((await audit()).labels)).not.toBe(JSON.stringify(initial.labels))
  await page.getByLabel('Alternate category palette').uncheck()
  await expect.poll(async () => (await audit()).colors).toEqual(initial.colors)
  await page.getByLabel('Flat routes + quiet ground').check()
  await expect.poll(async () => (await audit()).flatStrokes).toBeGreaterThanOrEqual(4)
  await page.getByLabel('Flat routes + quiet ground').uncheck()
  await expect.poll(async () => (await audit()).flatStrokes).toBe(0)
  await expect(page.getByTestId('study-time')).toHaveText('60 s')
})
