import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Transport heroes' }).click()
  await page.getByRole('combobox', { name: 'Hero presentation', exact: true }).selectOption('sbb')
})

test('SBB layout shows service, via stops, tracks and supported languages', async ({ page }) => {
  const hero = page.getByRole('region', { name: 'Zürich HB', exact: true })
  await expect(hero).toHaveAttribute('data-presentation', 'sbb')
  const board = hero.getByRole('table', { name: 'Zürich HB Abfahrt', exact: true })
  await expect(board.getByRole('columnheader', { name: 'Gleis', exact: true })).toBeVisible()
  await expect(board.getByRole('cell', { name: 'IC 1', exact: true })).toBeVisible()
  await expect(board.getByRole('cell', { name: '—', exact: true })).toHaveCount(1)
  const geneva = board.getByRole('button', { name: /^Genève-Aéroport/ })
  await expect(geneva).toContainText('Bern · Fribourg/Freiburg · Lausanne')
  await geneva.focus()
  await page.keyboard.press('Enter')
  await expect(geneva).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Update departure' }).evaluate((button: HTMLButtonElement) => button.click())
  await expect(geneva).toBeFocused()
  await expect(board.getByRole('cell', { name: /09:07.*\+8 min/ })).toBeVisible()
  for (const [language, heading, platform] of [['fr', 'Départ', 'Voie'], ['it', 'Partenza', 'Binario'], ['en', 'Departures', 'Platform']]) {
    await page.getByRole('combobox', { name: 'Board language', exact: true }).selectOption(language)
    await expect(hero.getByRole('table', { name: `Zürich HB ${heading}` })).toBeVisible()
    await expect(hero.getByRole('columnheader', { name: platform, exact: true })).toBeVisible()
    await expect(hero.getByRole('button', { name: /^Genève-Aéroport/ })).toHaveAttribute('aria-pressed', 'true')
  }
  await expect(hero).toContainText('Synthetic timetable')
  await expect(hero).not.toContainText('On time')
})

test('SBB rows fit fixed and auto heights, and contain long names on mobile', async ({ page }) => {
  const board = page.locator('.ms-sbb-board')
  await expect(board.locator('.ms-sbb-board__row')).toHaveCount(6)
  await page.getByRole('combobox', { name: 'Hero lines', exact: true }).selectOption('3')
  await expect(board.locator('.ms-sbb-board__row')).toHaveCount(3)
  await page.getByLabel('Long hero destination').check()
  await expect(board.getByRole('button', { name: /^Genève-Aéroport via Lausanne et Fribourg\/Freiburg/ })).toBeVisible()
  await page.locator('.transport-hero-specimen').evaluate((element) => { element.style.width = '300px' })
  await expect.poll(() => board.evaluate((element) => element.scrollWidth <= element.clientWidth && element.scrollHeight <= element.clientHeight)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('combobox', { name: 'Hero lines', exact: true }).selectOption('auto')
  await page.getByRole('slider', { name: 'Hero display height', exact: true }).press('End')
  await expect.poll(async () => Number(await board.getAttribute('data-lines'))).toBeGreaterThan(6)
  await page.getByRole('slider', { name: 'Hero display height', exact: true }).press('Home')
  await expect.poll(async () => Number(await board.getAttribute('data-lines'))).toBeLessThan(3)
})

test('SBB loading, empty and error states expose no stale departures', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const hero = page.getByRole('region', { name: 'Zürich HB', exact: true })
  await page.getByRole('combobox', { name: 'Hero state', exact: true }).selectOption('loading')
  await expect(hero.getByRole('table')).toHaveAttribute('aria-busy', 'true')
  await expect(hero.getByRole('status')).toHaveText('Abfahrten werden geladen…')
  await expect(hero.getByRole('button')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Hero state', exact: true }).selectOption('empty')
  await expect(hero.getByRole('status')).toHaveText('Keine Abfahrten in diesem Zeitraum.')
  await page.getByRole('combobox', { name: 'Hero state', exact: true }).selectOption('error')
  await expect(hero.getByRole('table')).toHaveCount(0)
  await hero.getByRole('button', { name: 'Erneut versuchen' }).click()
  await expect(hero.getByRole('table')).toHaveAttribute('aria-busy', 'false')
  await expect(hero.getByRole('button', { name: /^Genève-Aéroport/ })).toBeVisible()
  expect(await hero.evaluate((element) => element.getAnimations({ subtree: true }).length)).toBe(0)
})
