import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/') })

test('button help follows hover and keyboard focus, preserves descriptions and dismisses with Escape', async ({ page, isMobile }) => {
  const control = page.getByRole('button', { name: 'Vehicle labels', exact: true })
  const tooltip = page.getByRole('tooltip')
  if (isMobile) {
    await control.tap()
    await expect(control).toHaveText('L·A')
    await control.hover()
    await page.waitForTimeout(500)
    await expect(tooltip).toHaveCount(0)
    await expect(control).toHaveAttribute('aria-describedby', 'tooltip-note')
    await expect(page.locator('button[title]')).toHaveCount(0)
    return
  }
  await control.hover()
  await expect(tooltip).toHaveText('Show vehicle labels on the map')
  const id = await tooltip.getAttribute('id')
  await expect(control).toHaveAttribute('aria-describedby', `tooltip-note ${id}`)
  await tooltip.hover()
  await page.waitForTimeout(200)
  await expect(tooltip).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(tooltip).toHaveCount(0)
  await expect(control).toHaveAttribute('aria-describedby', 'tooltip-note')
  await page.waitForTimeout(500)
  await expect(tooltip).toHaveCount(0)
  await control.focus()
  await expect(tooltip).toHaveText('Show vehicle labels on the map')
  await control.press('Enter')
  await expect(tooltip).toHaveCount(0)
  await page.mouse.move(0, 0)
  await control.hover()
  await expect(tooltip).toHaveText('Hide vehicle labels on the map')
  await page.getByRole('button', { name: 'Clear', exact: true }).focus()
  await expect(tooltip).toHaveCount(0)
})

test('help explains disabled controls and stays inside the viewport', async ({ page, isMobile }) => {
  test.skip(isMobile, 'Hover-only help is intentionally absent on touch devices')
  const control = page.getByRole('button', { name: '↺', exact: true })
  await control.evaluate((element) => { Object.assign(element.style, { position: 'fixed', right: '8px', bottom: '8px' }) })
  await control.hover()
  const tooltip = page.getByRole('tooltip')
  await expect(tooltip).toHaveText('Reset is unavailable until a scene is mounted')
  const box = await tooltip.boundingBox()
  const viewport = page.viewportSize()!
  expect(box).not.toBeNull()
  expect(box!.x).toBeGreaterThanOrEqual(8)
  expect(box!.y).toBeGreaterThanOrEqual(8)
  expect(box!.x + box!.width).toBeLessThanOrEqual(viewport.width - 8)
  expect(box!.y + box!.height).toBeLessThanOrEqual(viewport.height - 8)
  await page.getByRole('button', { name: /Data$/ }).click()
  await expect(tooltip).toHaveCount(0)
})

test('touch input on a mouse-capable device clears help without blocking the control', async ({ page, isMobile }) => {
  test.skip(isMobile, 'The touch-only path is exercised separately')
  const control = page.getByRole('button', { name: 'Vehicle labels', exact: true })
  await control.hover()
  await expect(page.getByRole('tooltip')).toBeVisible()
  await control.dispatchEvent('pointerdown', { pointerType: 'touch' })
  await control.focus()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await page.keyboard.press('Tab')
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('tooltip')).toBeVisible()
})
