import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Transport heroes' }).click()
})

test('rail has matrix headings, attached service notes and stable selection across styles', async ({ page }) => {
  const hero = page.getByRole('region', { name: 'Bristol Temple Meads', exact: true })
  const board = hero.getByRole('table', { name: 'Bristol Temple Meads Departures' })
  await expect(hero.locator('.ms-dot-matrix-board')).toHaveAttribute('data-variant', 'uk-rail')
  await expect(board.getByRole('columnheader', { name: 'Plat', exact: true })).toBeVisible()
  await expect(board.getByRole('cell', { name: 'Cancelled', exact: true })).toBeVisible()
  const portsmouth = board.getByRole('button', { name: 'Portsmouth Harbour', exact: true })
  await expect(portsmouth).toHaveAccessibleDescription('via Eastleigh')
  await expect(hero.locator('.ms-dot-matrix-board__detail')).toHaveCount(2)
  await expect(hero.locator('.ms-dot-matrix-board__footer')).toContainText('16:49:26')
  const london = board.getByRole('button', { name: 'London Paddington', exact: true })
  await london.focus()
  await page.keyboard.press('Enter')
  await expect(london).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Update departure' }).evaluate((button: HTMLButtonElement) => button.click())
  await expect(london).toBeFocused()
  await expect(board.getByRole('cell', { name: '17:08', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Hero presentation', exact: true }).selectOption('split-flap')
  await expect(london).toHaveAttribute('aria-pressed', 'true')
  await expect(board.getByRole('cell', { name: 'Please use the front 5 coaches', exact: true })).toBeAttached()
  await page.getByRole('combobox', { name: 'Hero presentation', exact: true }).selectOption('uk-rail')
  await expect(london).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('selected-hero-departure')).toHaveText('Selected departure: rail-2')
})

test('line limits keep rail details together and narrow cards contain their content', async ({ page }) => {
  const hero = page.getByRole('region', { name: 'Bristol Temple Meads', exact: true })
  await page.getByRole('combobox', { name: 'Hero lines', exact: true }).selectOption('3')
  await expect(hero.locator('tbody tr')).toHaveCount(3)
  await expect(hero.getByRole('button')).toHaveCount(2)
  await expect(hero.locator('.ms-dot-matrix-board__detail')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Hero lines', exact: true }).selectOption('6')
  await expect(hero.locator('tbody tr')).toHaveCount(6)
  await expect(hero.getByRole('button', { name: 'Portsmouth Harbour', exact: true })).toHaveAccessibleDescription('via Eastleigh')
  await expect(hero.locator('.ms-dot-matrix-board__detail')).toHaveCount(2)
  await page.getByLabel('Long hero destination').check()
  await expect(hero.getByRole('button', { name: 'London Paddington via Bath Spa and Reading', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.locator('.transport-hero-specimen').evaluate((element) => { element.style.width = '300px' })
  await expect.poll(() => hero.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await expect.poll(() => hero.locator('.ms-dot-matrix-board__screen').evaluate((element) => element.scrollWidth <= element.clientWidth && element.scrollHeight <= element.clientHeight + 1)).toBe(true)
  await page.getByRole('combobox', { name: 'Hero lines', exact: true }).selectOption('auto')
  const before = Number(await hero.locator('[data-lines]').getAttribute('data-lines'))
  await page.getByRole('slider', { name: 'Hero display height', exact: true }).press('Home')
  await expect.poll(async () => Number(await hero.locator('[data-lines]').getAttribute('data-lines'))).toBeLessThan(before)
})

test('bus, rail and airport cards retain their own identity and domain fields', async ({ page }) => {
  await page.getByRole('combobox', { name: 'Transport', exact: true }).selectOption('bus')
  const bus = page.getByRole('region', { name: 'Anchor Road', exact: true })
  await expect(bus.locator('.ms-dot-matrix-board')).toHaveAttribute('data-variant', 'bus')
  await expect(bus.getByRole('columnheader', { name: 'Route', exact: true })).toBeVisible()
  await expect(bus.getByRole('columnheader', { name: 'Due', exact: true })).toBeVisible()
  await expect(bus).toContainText('A1')
  const route = bus.getByRole('button', { name: 'X9', exact: true })
  await expect(route).toHaveAccessibleDescription('via Long Ashton')
  await route.click()
  await expect(route).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('combobox', { name: 'Transport', exact: true }).selectOption('airport')
  const airport = page.getByRole('region', { name: 'Northfield International', exact: true })
  await expect(airport.getByRole('columnheader', { name: 'Flight', exact: true })).toBeVisible()
  await expect(airport.getByRole('columnheader', { name: 'Gate', exact: true })).toBeVisible()
  await airport.getByRole('button', { name: 'Arrivals', exact: false }).click()
  await expect(airport.getByRole('button', { name: 'NF 203' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Transport', exact: true }).selectOption('bus')
  await expect(bus.getByRole('button', { name: 'X9', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('both new cards handle loading, empty and failure without stale departures', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const transport of ['rail', 'bus']) {
    await page.getByRole('combobox', { name: 'Transport', exact: true }).selectOption(transport)
    const hero = page.locator('.transport-hero-specimen > section')
    await page.getByRole('combobox', { name: 'Hero state', exact: true }).selectOption('loading')
    await expect(hero.getByRole('table')).toHaveAttribute('aria-busy', 'true')
    await expect(hero.getByRole('status')).toHaveText(transport === 'rail' ? 'Loading rail departures…' : 'Loading bus departures…')
    await expect(hero.getByRole('button')).toHaveCount(0)
    await page.getByRole('combobox', { name: 'Hero state', exact: true }).selectOption('empty')
    await expect(hero.getByRole('status')).toHaveText(transport === 'rail' ? 'No trains expected.' : 'No buses expected.')
    await page.getByRole('combobox', { name: 'Hero state', exact: true }).selectOption('error')
    await expect(hero.getByRole('table')).toHaveCount(0)
    await hero.getByRole('button', { name: 'Retry', exact: true }).click()
    await expect(hero.getByRole('table')).toHaveAttribute('aria-busy', 'false')
    expect(await hero.evaluate((element) => element.getAnimations({ subtree: true }).length)).toBe(0)
  }
})
