import { expect, test } from '@playwright/test'
test.beforeEach(async ({ page }) => {
  await page.route('**/assets/*.json', async route => {
    const name = route.request().url().split('/').at(-1)!.split('.')[0]
    if (name === 'slow') await new Promise(resolve => setTimeout(resolve, 350))
    await route.fulfill({ status: name === 'fail' ? 503 : name === 'missing' ? 404 : 200,
      contentType: 'application/json', body: JSON.stringify(name === 'invalid' ? {} : { name }) })
  })
  await page.goto('/e2e/fixtures/shared-controllers.html')
})
test('assets are lazy, source-keyed, cancellable, validated and explicitly retryable', async ({ page }) => {
  const asset = page.getByTestId('asset')
  await expect(asset).toBeEmpty()
  await expect(asset).toHaveAttribute('data-loading', 'false')
  await page.getByRole('button', { name: 'Toggle asset' }).click()
  await expect(asset).toHaveText('a')
  await page.getByLabel('Asset', { exact: true }).selectOption('slow')
  await expect(asset).toBeEmpty()
  await page.getByRole('button', { name: 'Toggle asset' }).click()
  await page.getByLabel('Asset', { exact: true }).selectOption('b')
  await page.getByRole('button', { name: 'Toggle asset' }).click()
  await expect(asset).toHaveText('b')
  await page.waitForTimeout(400)
  await expect(asset).toHaveText('b')
  await page.getByLabel('Asset', { exact: true }).selectOption('fail')
  await expect(asset).toHaveAttribute('data-error', 'true')
  await page.route('**/assets/fail.json', route => route.fulfill({ json: { name: 'recovered' } }))
  await page.getByRole('button', { name: 'Retry asset' }).click()
  await expect(asset).toHaveText('recovered')
  await page.getByLabel('Asset', { exact: true }).selectOption('missing')
  await expect(asset).toHaveAttribute('data-unavailable', 'true')
  await expect(asset).toHaveAttribute('data-error', 'false')
  await page.getByLabel('Asset', { exact: true }).selectOption('invalid')
  await expect(asset).toHaveAttribute('data-error', 'true')
})
test('transitions reverse from the current frame and settle when reduced motion is enabled', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  const output = page.getByTestId('transition')
  await page.getByRole('button', { name: 'Transition', exact: true }).click()
  await expect(output).toHaveAttribute('data-active', 'true')
  await expect.poll(async () => Number(await output.textContent())).toBeGreaterThan(0)
  const before = Number(await output.textContent())
  await page.getByRole('button', { name: 'Transition', exact: true }).click()
  expect(Number(await output.textContent())).toBeLessThan(0.8)
  expect(before).toBeLessThan(1)
  await expect(output).toHaveText('0.000')
  await page.getByRole('button', { name: 'Transition', exact: true }).click()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(output).toHaveText('1.000')
  await expect(output).toHaveAttribute('data-active', 'false')
})
